-------------TASKS 1.1 & 1.2----------------------------------------------
DROP TABLE A2ERROREVENT CASCADE CONSTRAINTS;
DROP SEQUENCE A2ERROREVENTSEQUENCE;
DROP TABLE DWPROD CASCADE CONSTRAINTS;
DROP SEQUENCE DWPRODSEQUENCE;
DROP TABLE DWCUST CASCADE CONSTRAINTS;
DROP SEQUENCE DWCUSTSEQUENCE;
DROP TABLE DWSALE CASCADE CONSTRAINTS;
DROP SEQUENCE DWSALESEQUENCE;
DROP TABLE GENDERSPELLING CASCADE CONSTRAINTS;


CREATE TABLE A2ERROREVENT ( 
	ERRORID  INTEGER, 
	SOURCE_ROWID  ROWID,  
	SOURCE_TABLE   VARCHAR2(30),  
	FILTERID       INTEGER,  
	DATETIME       DATE,  
	ACTION          VARCHAR2(6), 
	CONSTRAINT    ERROREVENTACTION  CHECK (ACTION IN ('SKIP','MODIFY')) 
);
CREATE SEQUENCE A2ERROREVENTSEQUENCE;

CREATE TABLE DWPROD (
	DWPRODID NUMBER(38),
	DWSOURCETABLE VARCHAR2(30),
	DWSOURCEID NUMBER(38),
	PRODNAME VARCHAR2(100),
	PRODCATNAME VARCHAR2(30),
	PRODMANUNAME VARCHAR2(30),
	PRODSHIPNAME VARCHAR2(30),
	PRIMARY KEY (DWPRODID)
);
CREATE SEQUENCE DWPRODSEQUENCE;

CREATE TABLE DWCUST (
	DWCUSTID NUMBER(38),
	DWSOURCEIDBRIS VARCHAR2(100),
	DWSOURCEIDMELB VARCHAR2(100),
	FIRSTNAME VARCHAR2(30),
	SURNAME VARCHAR2(30),
	GENDER VARCHAR2(10),
	PHONE NUMBER(12),
	POSTCODE NUMBER(4),
	CITY VARCHAR2(50),
	STATE VARCHAR2(10),
	CUSTCATNAME VARCHAR2(30),
	PRIMARY KEY (DWCUSTID)
);
CREATE SEQUENCE DWCUSTSEQUENCE;

CREATE TABLE DWSALE (
	DWSALEID NUMBER(38),
	DWCUSTID NUMBER(38),
	DWPRODID NUMBER(38),
	DWSOURCEIDBRIS VARCHAR2(100),
	DWSOURCEIDMELB VARCHAR2(100),
	QTY NUMBER(2),
	SALE_DWDATEID NUMBER(38),
	SHIP_DWDATEID NUMBER(38),
	SALEPRICE NUMBER(7,2),
	PRIMARY KEY (DWSALEID)
);
CREATE SEQUENCE DWSALESEQUENCE;
-------------TASK 1.3----------------------------------------------
CREATE TABLE GENDERSPELLING (
	INVALIDVALUE VARCHAR2(50),
	NEWVALUE VARCHAR2(50)
);
/
INSERT INTO GENDERSPELLING (INVALIDVALUE, NEWVALUE)
VALUES ('MAIL', 'M');

INSERT INTO GENDERSPELLING (INVALIDVALUE, NEWVALUE)
VALUES ('WOMAN', 'F');
	
INSERT INTO GENDERSPELLING (INVALIDVALUE, NEWVALUE)
VALUES ('FEM', 'F');
	
INSERT INTO GENDERSPELLING (INVALIDVALUE, NEWVALUE)
VALUES ('FEMALE', 'F');
	
INSERT INTO GENDERSPELLING (INVALIDVALUE, NEWVALUE)
VALUES ('MALE', 'M');
	
INSERT INTO GENDERSPELLING (INVALIDVALUE, NEWVALUE)
VALUES ('GENTLEMAN', 'M');
	
INSERT INTO GENDERSPELLING (INVALIDVALUE, NEWVALUE)
VALUES ('MM', 'M');
	
INSERT INTO GENDERSPELLING (INVALIDVALUE, NEWVALUE)
VALUES ('FF', 'F');

INSERT INTO GENDERSPELLING(INVALIDVALUE, NEWVALUE)
VALUES ('FEMAIL', 'F');
/
-------------TASK 2.1----------------------------------------------
INSERT INTO A2ERROREVENT (ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ACTION)
SELECT A2ERROREVENTSEQUENCE.NEXTVAL, P.ROWID, 'A2PRODUCT', 1, SYSDATE, 'SKIP'
FROM A2PRODUCT P
WHERE P.PRODNAME IS NULL;
/
-------------TASK 2.2----------------------------------------------
INSERT INTO A2ERROREVENT (ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ACTION)
SELECT A2ERROREVENTSEQUENCE.NEXTVAL, P.ROWID, 'A2PRODUCT', 2, SYSDATE, 'MODIFY'
FROM A2PRODUCT P
WHERE P.MANUFACTURERCODE IS NULL;
/
-------------TASK 2.3------------------------------------------------
INSERT INTO A2ERROREVENT (ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ACTION)
SELECT A2ERROREVENTSEQUENCE.NEXTVAL, P.ROWID, 'A2PRODUCT', 3, SYSDATE, 'MODIFY'
FROM A2PRODUCT P
WHERE P.PRODCATEGORY IS NULL OR P.PRODCATEGORY NOT IN (SELECT PC.PRODUCTCATEGORY FROM A2PRODCATEGORY PC);
/
-------------TASK 2.4.3----------------------------------------------
INSERT INTO DWPROD(DWPRODID, DWSOURCETABLE, DWSOURCEID, PRODNAME, PRODCATNAME, PRODMANUNAME, PRODSHIPNAME)
SELECT DWPRODSEQUENCE.NEXTVAL, 'A2PRODUCT', A.PRODID, A.PRODNAME, A.PRODCATEGORY, A.MANUFACTURERCODE, A.SHIPPINGCODE
FROM A2PRODUCT A
WHERE A.ROWID NOT IN (SELECT SOURCE_ROWID FROM A2ERROREVENT);
/
-------------TASK 2.4.4----------------------------------------------
INSERT INTO DWPROD (DWPRODID, DWSOURCETABLE, DWSOURCEID, PRODNAME, PRODCATNAME, PRODMANUNAME, PRODSHIPNAME)
SELECT DWPRODSEQUENCE.NEXTVAL, 'A2PRODUCT', A.PRODID, A.PRODNAME, A.PRODCATEGORY, 'UNKNOWN', A.SHIPPINGCODE
FROM A2PRODUCT A
WHERE A.ROWID IN (SELECT SOURCE_ROWID FROM A2ERROREVENT WHERE FILTERID = 2);
/
-------------TASK 2.4.5----------------------------------------------
INSERT INTO DWPROD (DWPRODID, DWSOURCETABLE, DWSOURCEID, PRODNAME, PRODCATNAME, PRODMANUNAME, PRODSHIPNAME)
SELECT DWPRODSEQUENCE.NEXTVAL, 'A2PRODUCT', A.PRODID, A.PRODNAME, 'UNKNOWN', A.MANUFACTURERCODE, A.SHIPPINGCODE
FROM A2PRODUCT A
WHERE A.ROWID IN (SELECT SOURCE_ROWID FROM A2ERROREVENT WHERE FILTERID = 3);
/
------------------ Part 3 ---------------------
------------------ TASK 3.1 -------------------
INSERT INTO A2ERROREVENT (ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ACTION)
	SELECT	A2ERROREVENTSEQUENCE.nextval, ROWID, 'A2CUSTBRIS', 4, SYSDATE, 'MODIFY'
	FROM	A2CUSTBRIS a
	WHERE	a.CUSTCATCODE is null
	or a.CUSTCATCODE NOT IN (SELECT CUSTCATCODE FROM A2CUSTCATEGORY);	
/
------------------ TASK 3.2 -------------------		
INSERT INTO A2ERROREVENT (ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ACTION)
	SELECT	A2ERROREVENTSEQUENCE.nextval, ROWID, 'A2CUSTBRIS', 5, SYSDATE, 'MODIFY'
	FROM	A2CUSTBRIS a
	WHERE	a.PHONE LIKE '%-%'
	or		a.PHONE LIKE '% %';	
/
------------------ TASK 3.3 -------------------		
INSERT INTO A2ERROREVENT (ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ACTION)
	SELECT	A2ERROREVENTSEQUENCE.nextval, ROWID, 'A2CUSTBRIS', 6, SYSDATE, 'SKIP'
	FROM	A2CUSTBRIS a
	WHERE NOT LENGTH(a.PHONE) = 10
	AND NOT (a.PHONE LIKE '%-%' OR a.PHONE LIKE '% %');
/	
------------------ TASK 3.4 -------------------		
INSERT INTO A2ERROREVENT (ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ACTION)
	SELECT	A2ERROREVENTSEQUENCE.nextval, ROWID, 'A2CUSTBRIS', 7, SYSDATE, 'MODIFY'
	FROM	A2CUSTBRIS a
	WHERE a.GENDER is null
	OR NOT (a.GENDER = 'F' or a.GENDER = 'M' or a.GENDER = 'f' or a.GENDER = 'm');
/	
------------------ TASK 3.5.1 -------------------		
INSERT INTO DWCUST (DWCUSTID, DWSOURCEIDBRIS, DWSOURCEIDMELB, FIRSTNAME, SURNAME, GENDER, PHONE, POSTCODE, CITY, STATE, CUSTCATNAME)
	SELECT	DWCUSTSEQUENCE.nextval, a.CUSTID, NULL, a.FNAME, a.SNAME, UPPER(a.GENDER), a.PHONE, a.POSTCODE, a.CITY, a.STATE, b.CUSTCATNAME
	FROM	A2CUSTBRIS a
	INNER JOIN A2CUSTCATEGORY b ON a.CUSTCATCODE = b.CUSTCATCODE
	WHERE  a.ROWID NOT IN (
		SELECT SOURCE_ROWID
		FROM A2ERROREVENT
		WHERE SOURCE_TABLE = 'A2CUSTBRIS');
/		
------------------ TASK 3.5.2 -------------------		
INSERT INTO DWCUST (DWCUSTID, DWSOURCEIDBRIS, DWSOURCEIDMELB, FIRSTNAME, SURNAME, GENDER, PHONE, POSTCODE, CITY, STATE, CUSTCATNAME)
	SELECT	DWCUSTSEQUENCE.nextval, a.CUSTID, NULL, a.FNAME, a.SNAME, UPPER(a.GENDER), a.PHONE, a.POSTCODE, a.CITY, a.STATE, 'UNKNOWN'
	FROM	A2CUSTBRIS a
	WHERE a.ROWID IN (SELECT SOURCE_ROWID FROM A2ERROREVENT
					WHERE SOURCE_TABLE = 'A2CUSTBRIS' AND FILTERID = 4);
/	
------------------ TASK 3.5.3 -------------------		
INSERT INTO DWCUST (DWCUSTID, DWSOURCEIDBRIS, DWSOURCEIDMELB, FIRSTNAME, SURNAME, GENDER, 
					PHONE, POSTCODE, CITY, STATE, CUSTCATNAME)
	SELECT	DWCUSTSEQUENCE.nextval, a.CUSTID, NULL, a.FNAME, a.SNAME, UPPER(a.GENDER),
					REPLACE(REPLACE(a.PHONE, ' '), '-'), a.POSTCODE, a.CITY, a.STATE, b.CUSTCATNAME
	FROM	A2CUSTBRIS a
	INNER JOIN A2CUSTCATEGORY b ON a.CUSTCATCODE = b.CUSTCATCODE
	WHERE	a.ROWID IN (SELECT SOURCE_ROWID FROM A2ERROREVENT
						WHERE SOURCE_TABLE = 'A2CUSTBRIS' AND FILTERID = 5);
/		
------------------ TASK 3.5.4 -------------------		
INSERT INTO DWCUST (DWCUSTID, DWSOURCEIDBRIS, DWSOURCEIDMELB, FIRSTNAME, SURNAME, GENDER, PHONE, POSTCODE, CITY, STATE, CUSTCATNAME)
	SELECT	DWCUSTSEQUENCE.nextval, a.CUSTID, NULL, a.FNAME, a.SNAME, NVL(
				(SELECT b.NEWVALUE 
				FROM  GENDERSPELLING b 
				WHERE b.INVALIDVALUE = UPPER(a.GENDER)) , 'U'), 
				REPLACE(REPLACE(a.PHONE, ' '), '-'),
			a.POSTCODE, a.CITY, a.STATE, c.CUSTCATNAME
	FROM	A2CUSTBRIS a
	INNER JOIN A2CUSTCATEGORY c ON a.CUSTCATCODE = c.CUSTCATCODE
	WHERE	a.ROWID IN (
		SELECT SOURCE_ROWID
		FROM A2ERROREVENT
		WHERE FILTERID = 7
		AND SOURCE_TABLE = 'A2CUSTBRIS');
/
------------------ TASK 4 -------------------
UPDATE DWCUST a
    SET a.DWSOURCEIDMELB = (  SELECT b.CUSTID
                            FROM A2CUSTMELB b
                            WHERE b.FNAME = a.FIRSTNAME
                            AND	b.SNAME = a.SURNAME
                            AND	b.POSTCODE = a.POSTCODE);


INSERT INTO DWCUST (DWCUSTID, DWSOURCEIDBRIS, DWSOURCEIDMELB, FIRSTNAME, SURNAME, GENDER, PHONE, POSTCODE, CITY, STATE, CUSTCATNAME)
	SELECT	DWCUSTSEQUENCE.nextval, NULL, a.CUSTID, a.FNAME, a.SNAME, a.GENDER, a.PHONE, a.POSTCODE, a.CITY, a.STATE, b.CUSTCATNAME
	FROM	A2CUSTMELB a
	INNER JOIN A2CUSTCATEGORY b ON a.CUSTCATCODE = b.CUSTCATCODE
	WHERE	a.CUSTID NOT IN (
		SELECT DWSOURCEIDMELB
		FROM DWCUST c
		WHERE a.FNAME = c.FIRSTNAME
        AND	a.SNAME = c.SURNAME
        AND	a.POSTCODE = c.POSTCODE);
/
------------------ Part 5 ---------------------
------------------ TASK 5.1 -------------------
INSERT INTO A2ERROREVENT (ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ACTION)
	SELECT	A2ERROREVENTSEQUENCE.nextval, ROWID, 'A2SALEBRIS', 8, SYSDATE, 'SKIP'
	FROM	A2SALEBRIS a
	WHERE	a.PRODID is null
	or a.PRODID NOT IN (SELECT DWSOURCEID FROM DWPROD);	
/ 
------------------ TASK 5.2 -------------------
INSERT INTO A2ERROREVENT (ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ACTION)
	SELECT	A2ERROREVENTSEQUENCE.nextval, ROWID, 'A2SALEBRIS', 9, SYSDATE, 'SKIP'
	FROM	A2SALEBRIS a
	WHERE	a.CUSTID is null
	or a.CUSTID NOT IN (SELECT DWSOURCEIDBRIS FROM DWCUST
						WHERE DWSOURCEIDBRIS is not null);	
/
------------------ TASK 5.3 -------------------
INSERT INTO A2ERROREVENT (ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ACTION)
	SELECT	A2ERROREVENTSEQUENCE.nextval, ROWID, 'A2SALEBRIS', 10, SYSDATE, 'MODIFY'
	FROM	A2SALEBRIS a
	WHERE	a.SHIPDATE is null
	or a.CUSTID IN (SELECT CUSTID FROM DWCUST
						WHERE SHIPDATE < SALEDATE);	
/ 
------------------ TASK 5.4 -------------------
INSERT INTO A2ERROREVENT (ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ACTION)
	SELECT	A2ERROREVENTSEQUENCE.nextval, ROWID, 'A2SALEBRIS', 11, SYSDATE, 'MODIFY'
	FROM	A2SALEBRIS a
	WHERE	a.UNITPRICE is null;	
/ 
------------------ TASK 5.5 -------------------		
INSERT INTO DWSALE (DWSALEID, DWCUSTID, DWPRODID, DWSOURCEIDBRIS, DWSOURCEIDMELB, QTY, SALE_DWDATEID, SHIP_DWDATEID, SALEPRICE)
	SELECT	DWSALESEQUENCE.nextval, b.DWCUSTID, c.DWPRODID, a.SALEID, null, a.QTY, d.DATEKEY, e.DATEKEY, a.UNITPRICE
	FROM	A2SALEBRIS a
    INNER JOIN DWCUST b ON a.CUSTID = b.DWSOURCEIDBRIS
	INNER JOIN DWPROD c on a.PRODID = c.DWSOURCEID
	INNER JOIN DWDATE d ON a.SALEDATE = d.DATEVALUE
	INNER JOIN DWDATE e ON a.SHIPDATE = e.DATEVALUE
	WHERE a.ROWID NOT IN (
		SELECT SOURCE_ROWID
		FROM A2ERROREVENT
		WHERE SOURCE_TABLE = 'A2SALEBRIS');
/							
------------------ TASK 5.6 -------------------		
INSERT INTO DWSALE (DWSALEID, DWCUSTID, DWPRODID, DWSOURCEIDBRIS, DWSOURCEIDMELB, QTY, SALE_DWDATEID, SHIP_DWDATEID, SALEPRICE)
	SELECT	DWSALESEQUENCE.nextval, b.DWCUSTID, c.DWPRODID, a.SALEID, null, a.QTY, d.DATEKEY, e.DATEKEY, a.UNITPRICE
	FROM	A2SALEBRIS a
    INNER JOIN DWCUST b ON a.CUSTID = b.DWSOURCEIDBRIS
	INNER JOIN DWPROD c on a.PRODID = c.DWSOURCEID
	INNER JOIN DWDATE d ON a.SALEDATE = d.DATEVALUE
	INNER JOIN DWDATE e ON a.SALEDATE + 2 = e.DATEVALUE
	WHERE a.ROWID IN (
		SELECT SOURCE_ROWID
		FROM A2ERROREVENT
		WHERE SOURCE_TABLE = 'A2SALEBRIS'
		AND FILTERID = 10);
/	
------------------ TASK 5.7 -------------------		
INSERT INTO DWSALE (DWSALEID, DWCUSTID, DWPRODID, DWSOURCEIDBRIS, DWSOURCEIDMELB, QTY, SALE_DWDATEID, SHIP_DWDATEID, SALEPRICE)
	SELECT	DWSALESEQUENCE.nextval, b.DWCUSTID, c.DWPRODID, a.SALEID, null, a.QTY, d.DATEKEY, e.DATEKEY, (SELECT MAX(UNITPRICE)
																											FROM A2SALEBRIS)
	FROM	A2SALEBRIS a
    INNER JOIN DWCUST b ON a.CUSTID = b.DWSOURCEIDBRIS
	INNER JOIN DWPROD c on a.PRODID = c.DWSOURCEID
	INNER JOIN DWDATE d ON a.SALEDATE = d.DATEVALUE
	INNER JOIN DWDATE e ON a.SALEDATE = e.DATEVALUE
	WHERE a.ROWID IN (
		SELECT SOURCE_ROWID
		FROM A2ERROREVENT
		WHERE SOURCE_TABLE = 'A2SALEBRIS'
		AND FILTERID = 11);
/
------------------ Part 6 ---------------------
------------------ TASK 6.1 -------------------
INSERT INTO A2ERROREVENT (ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ACTION)
	SELECT	A2ERROREVENTSEQUENCE.nextval, ROWID, 'A2SALEMELB', 12, SYSDATE, 'SKIP'
	FROM	A2SALEMELB a
	WHERE	a.PRODID is null
	or a.PRODID NOT IN (SELECT DWSOURCEID FROM DWPROD);	
/
------------------ TASK 6.2 -------------------
INSERT INTO A2ERROREVENT (ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ACTION)
	SELECT	A2ERROREVENTSEQUENCE.nextval, ROWID, 'A2SALEMELB', 13, SYSDATE, 'SKIP'
	FROM	A2SALEMELB a
	WHERE	a.CUSTID is null
	or a.CUSTID NOT IN (SELECT DWSOURCEIMELB FROM DWCUST
						WHERE DWSOURCEIDMELB is not null);	
/
------------------ TASK 6.3 -------------------
INSERT INTO A2ERROREVENT (ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ACTION)
	SELECT	A2ERROREVENTSEQUENCE.nextval, ROWID, 'A2SALEMELB', 14, SYSDATE, 'MODIFY'
	FROM	A2SALEMELB a
	WHERE	a.SHIPDATE is null
	or a.CUSTID IN (SELECT CUSTID FROM DWCUST
						WHERE SHIPDATE < SALEDATE);	
/
------------------ TASK 6.4 -------------------
INSERT INTO A2ERROREVENT (ERRORID, SOURCE_ROWID, SOURCE_TABLE, FILTERID, DATETIME, ACTION)
	SELECT	A2ERROREVENTSEQUENCE.nextval, ROWID, 'A2SALEMELB', 15, SYSDATE, 'MODIFY'
	FROM	A2SALEBRIS a
	WHERE	a.UNITPRICE is null;	
/
------------------ TASK 6.5 -------------------		
INSERT INTO DWSALE (DWSALEID, DWCUSTID, DWPRODID, DWSOURCEIDBRIS, DWSOURCEIDMELB, QTY, SALE_DWDATEID, SHIP_DWDATEID, SALEPRICE)
	SELECT	DWSALESEQUENCE.nextval, b.DWCUSTID, c.DWPRODID, null, a.SALEID, a.QTY, d.DATEKEY, e.DATEKEY, a.UNITPRICE
	FROM	A2SALEBRIS a
    INNER JOIN DWCUST b ON a.CUSTID = b.DWSOURCEIDMELB
	INNER JOIN DWPROD c on a.PRODID = c.DWSOURCEID
	INNER JOIN DWDATE d ON a.SALEDATE = d.DATEVALUE
	INNER JOIN DWDATE e ON a.SHIPDATE = e.DATEVALUE
	WHERE a.ROWID NOT IN (
		SELECT SOURCE_ROWID
		FROM A2ERROREVENT
		WHERE SOURCE_TABLE = 'A2SALEMELB');
/							
------------------ TASK 6.6 -------------------		
INSERT INTO DWSALE (DWSALEID, DWCUSTID, DWPRODID, DWSOURCEIDBRIS, DWSOURCEIDMELB, QTY, SALE_DWDATEID, SHIP_DWDATEID, SALEPRICE)
	SELECT	DWSALESEQUENCE.nextval, b.DWCUSTID, c.DWPRODID, null, a.SALEID, a.QTY, d.DATEKEY, e.DATEKEY, a.UNITPRICE
	FROM	A2SALEBRIS a
    INNER JOIN DWCUST b ON a.CUSTID = b.DWSOURCEIDMELB
	INNER JOIN DWPROD c on a.PRODID = c.DWSOURCEID
	INNER JOIN DWDATE d ON a.SALEDATE = d.DATEVALUE
	INNER JOIN DWDATE e ON a.SALEDATE + 2 = e.DATEVALUE
	WHERE a.ROWID IN (
		SELECT SOURCE_ROWID
		FROM A2ERROREVENT
		WHERE SOURCE_TABLE = 'A2SALEMELB'
		AND FILTERID = 14);
/	
------------------ TASK 6.7 -------------------		
INSERT INTO DWSALE (DWSALEID, DWCUSTID, DWPRODID, DWSOURCEIDBRIS, DWSOURCEIDMELB, QTY, SALE_DWDATEID, SHIP_DWDATEID, SALEPRICE)
	SELECT	DWSALESEQUENCE.nextval, b.DWCUSTID, c.DWPRODID, null, a.SALEID, a.QTY, d.DATEKEY, e.DATEKEY, (SELECT MAX(UNITPRICE)
																											FROM A2SALEMELB)
	FROM	A2SALEBRIS a
    INNER JOIN DWCUST b ON a.CUSTID = b.DWSOURCEIDMELB
	INNER JOIN DWPROD c on a.PRODID = c.DWSOURCEID
	INNER JOIN DWDATE d ON a.SALEDATE = d.DATEVALUE
	INNER JOIN DWDATE e ON a.SALEDATE = e.DATEVALUE
	WHERE a.ROWID IN (
		SELECT SOURCE_ROWID
		FROM A2ERROREVENT
		WHERE SOURCE_TABLE = 'A2SALEMELB'
		AND FILTERID = 15);
/  
			
		
		
		
		